# Generated by Django 6.0.4 on 2026-05-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillSummaryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=50, unique=True, verbose_name='의안번호')),
                ('summary_text', models.TextField(verbose_name='3줄 요약')),
                ('tag1', models.CharField(blank=True, max_length=50, null=True, verbose_name='태그1')),
                ('tag2', models.CharField(blank=True, max_length=50, null=True, verbose_name='태그2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
        ),
    ]
